DROP TABLE IF EXISTS ExplainMbti;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS Owner;
DROP TABLE IF EXISTS Guest;
DROP TABLE IF EXISTS account;


CREATE TABLE `ExplainMbti`
(
    `EXPLAINMBTI_MBTI` varchar(255) NOT NULL,
    `EXPLAINMBTI_NM`   varchar(255) DEFAULT NULL,
    `EXPLAINMBTI_CT`   varchar(255) DEFAULT NULL,
    PRIMARY KEY (`EXPLAINMBTI_MBTI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Question`
(
    `QUESTION_ID`   int NOT NULL AUTO_INCREMENT,
    `QUESTION_TYPE` varchar(45) COLLATE utf8mb3_bin  DEFAULT NULL,
    `QUESTION_CT`   varchar(500) COLLATE utf8mb3_bin DEFAULT NULL,
    `QUESTION_A1`   varchar(500) COLLATE utf8mb3_bin DEFAULT NULL,
    `QUESTION_A2`   varchar(500) COLLATE utf8mb3_bin DEFAULT NULL,
    PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `Owner`
(
    `OWNER_ID`       int         NOT NULL AUTO_INCREMENT,
    `OWNER_NICKNAME` varchar(45) NOT NULL,
    `OWNER_EMAIL`    varchar(45) DEFAULT NULL,
    `OWNER_ANS`      varchar(45)  DEFAULT NULL,
    `OWNER_MBTI`     varchar(45)  DEFAULT NULL,
    PRIMARY KEY (`OWNER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Guest`
(
    `GUEST_ID`       int         NOT NULL AUTO_INCREMENT,
    `GUEST_NICKNAME` varchar(45) NOT NULL,
    `GUEST_ANS`      varchar(45)  DEFAULT NULL,
    `RESULT_MBTI`     varchar(45)  DEFAULT NULL,
    PRIMARY KEY (`GUEST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

